blank_issues_enabled: true
contact_links:
  - name: Questions and ideas
    url: https://github.com/luisg0nc/portinhola/discussions
    about: Not sure it's a bug or a concrete feature? Start a discussion.
