"""readings and contract windows

Revision ID: 11bc7af036c7
Revises: 997bf61d0cd4
Create Date: 2026-07-27 17:21:15.503236

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11bc7af036c7'
down_revision: str | Sequence[str] | None = '997bf61d0cd4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_point_id', sa.Integer(), nullable=False),
    sa.Column('register', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['supply_point_id'], ['supply_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('reading_day_start', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('reading_day_end', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('submit_url', sa.String(), nullable=False))
    op.add_column('contracts', sa.Column('submit_phone', sa.String(), nullable=False))
    op.add_column('contracts', sa.Column('submit_reference', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'submit_reference')
    op.drop_column('contracts', 'submit_phone')
    op.drop_column('contracts', 'submit_url')
    op.drop_column('contracts', 'reading_day_end')
    op.drop_column('contracts', 'reading_day_start')
    op.drop_table('readings')
    # ### end Alembic commands ###
