"""supply points, contracts, bills

Revision ID: 31bdaf454104
Revises: a6e3a1710f4f
Create Date: 2026-07-27 14:04:12.040676

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31bdaf454104'
down_revision: str | Sequence[str] | None = 'a6e3a1710f4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_nif', sa.String(), nullable=False),
    sa.Column('customer_nif', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('doc_number', sa.String(), nullable=False),
    sa.Column('atcud', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('vat_json', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('extractor', sa.String(), nullable=True),
    sa.Column('qr_raw', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atcud')
    )
    op.create_table('supply_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_point_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('supplier_nif', sa.String(), nullable=False),
    sa.Column('tariff_name', sa.String(), nullable=False),
    sa.Column('power_kva', sa.Float(), nullable=True),
    sa.Column('cycle', sa.String(), nullable=True),
    sa.Column('gas_tier', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['supply_point_id'], ['supply_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('vat_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_lines')
    op.drop_table('contracts')
    op.drop_table('supply_points')
    op.drop_table('bills')
    # ### end Alembic commands ###
