"""interval consumption

Revision ID: 997bf61d0cd4
Revises: 2a4d801ddc4f
Create Date: 2026-07-27 16:02:05.655552

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '997bf61d0cd4'
down_revision: str | Sequence[str] | None = '2a4d801ddc4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interval_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_point_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['supply_point_id'], ['supply_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supply_point_id', 'ts')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interval_consumption')
    # ### end Alembic commands ###
